### ISSUE TITLE
Support windows runners

### ISSUE THREAD

**Issue by corymhall** [pulumi/esc-action#10]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We have some jobs that run on the `windows-latest` runner and it looks like this action does not currently support running on windows.

```console
Run pulumi/esc-action@41fd832f44f4820124b5350b5f84a00f741f234e
Installing ESC CLI
  "C:\Program Files\Git\bin\sh.exe" -c "curl -fsSL https://get.pulumi.com/esc/install.sh | sh"
  error: We're sorry, but it looks like Pulumi ESC is not supported on your platform
         We support 64-bit versions of Linux and macOS and are interested in supporting
         more platforms.  Please open an issue at https://github.com/pulumi/esc and
         let us know what platform you're using!
  
  We're sorry, but it looks like something might have gone wrong during installation.
  If you need help, please join us on https://slack.pulumi.com/
  Error: The process 'C:\Program Files\Git\bin\sh.exe' failed with exit code 1
```

See this workflow run as an example https://github.com/pulumi/pulumi-aws-apigateway/actions/runs/14065622149/job/39388161760

**Comment by corymhall** [comment]
A workaround is to use this step to first manually install esc

```yaml
      - name: Install esc on Windows
        if: ${{ matrix.runner == 'windows-latest' }}
        shell: pwsh
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          iex ((New-Object System.Net.WebClient).DownloadString('https://get.pulumi.com/esc/install.ps1'))
          Copy-Item "$env:USERPROFILE\.pulumi\bin\esc.exe" "C:\Windows\System32\esc.exe"

```
