### ISSUE TITLE
Env variable injection breaks if value contains `=`

### ISSUE THREAD

**Issue by andysmith415** [pulumi/esc-action#29]
### What happened?

Using `pulumi/esc-action@efb0bc8946938f0dfbfa00e829196ec95f0d0ea` to inject my ESC env variables into a Github Action.

One of my env variables is the of the form `FOO_BAR=foo=bar`. When accessing the variable, it shows that only the first half of the variable is used `FOO_BAR=foo`; the `=bar` is truncated.

### Example

Minimal repo: 
- Have an env variable set to FOO_BAR=foo=bar

GHA
```
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Install and inject ESC environment variables
        # Pin to https://github.com/pulumi/esc-action/tree/v1.4.0
        uses: pulumi/esc-action@efb0bc8946938f0dfbfa00e829196ec95f0d0ea7
        with:
          environment: my-org/my-env

      - name: Test truncate bug
        run: |
          if [ "$FOO_BAR" == "foo" ]; then
            echo "Env variable was truncated"
          fi
          
```

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.169.0
Go Version   go1.24.3
Go Compiler  gc

Host
OS       darwin
Version  15.4.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
